# Generated by Django 3.2 on 2021-04-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Attachments',
            new_name='CustomerAttachments',
        ),
    ]
