# Generated by Django 3.2 on 2021-04-29 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customerattachments_customer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerattachments',
            name='customer_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer'),
        ),
    ]
