# Generated by Django 3.2 on 2021-04-30 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_alter_customer_help_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerattachments',
            options={'verbose_name_plural': 'CustomerAttachments'},
        ),
        migrations.AddField(
            model_name='customer',
            name='support',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='verify',
            field=models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='لا', max_length=3),
        ),
        migrations.AlterField(
            model_name='customer',
            name='help_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Money', 'مال'), ('Food', 'طعام'), ('Medicine', 'دواء')], max_length=19),
        ),
        migrations.CreateModel(
            name='CustomerHandel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('handel_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CustomerHandel',
            },
        ),
    ]
