# Generated by Django 3.2 on 2021-04-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210430_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='verify',
            field=models.CharField(choices=[('Yes', 'نعم'), ('No', 'لا')], default='No', max_length=3),
        ),
    ]
