# Generated by Django 3.2 on 2021-04-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_customer_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='verify',
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('hold', 'بالإنتظار'), ('verify', 'تأكيد البيانات'), ('handling', 'تتم المساعده'), ('done', 'تمت المساعده')], default='hold', max_length=9),
        ),
    ]
