# Generated by Django 3.2 on 2021-04-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210430_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
