# Generated by Django 3.2 on 2021-04-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210430_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='comment',
        ),
    ]
