# Generated by Django 3.2 on 2021-05-01 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_customerhandel_customer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerhandel',
            name='customer_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.customer'),
        ),
    ]
